"""Type stubs for sprag.runtime.app."""

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Optional, Union

from .mount import Mount
from .page import Page
from .session import SessionPolicy


@dataclass
class App:
    """Application container for a SPRAG project.

    Create this once in ``app/__init__.py``. Configure providers, route and
    mount packages, the app shell, global modules, metadata, sessions, uploads,
    and server mode. Use ``build(...)`` for static output and ``serve(...)``
    for local/runtime serving.
    """

    providers: dict[str, Any] = ...
    routes: str = ...
    mounts_package: str = ...
    project_root: Optional[str] = ...
    shell: object = ...
    modules: dict[str, Any] = ...
    metadata: dict[str, Any] = ...
    server_mode: str = ...
    session_policy: SessionPolicy = ...
    upload_chunk_size: int = ...
    upload_temp_dir: Optional[str] = ...

    def pages(self) -> list[tuple[str, Page]]: ...
    def mounts(self) -> list[tuple[str, Mount]]: ...
    def invalidate_pages(self) -> None: ...
    def upload_manager(self) -> Any: ...
    def boot(self) -> None: ...
    def shutdown(self) -> None: ...
    def controller_for_page(self, page: Page) -> Any: ...
    def controller_for_mount(self, mount: Mount) -> Any: ...
    def build(self, output_dir: Union[str, Path] = ...) -> dict[str, Any]:
        """Build discovered pages and mounts into a static output directory."""
        ...
    def serve(
        self,
        *,
        host: str = ...,
        port: int = ...,
        build_dir: Union[str, Path] = ...,
        max_workers: int = ...,
        server_mode: Optional[str] = ...,
    ) -> None:
        """Run the app locally with WSGI or websocket support."""
        ...
    def socket_bridge(self) -> Any: ...
    def runtime_root(self) -> Any: ...
