"""Type stubs for sprag.runtime.browser.

These describe the **browser-side** authoring surface. The runtime methods
all raise ``RuntimeError`` in plain Python — they only do real work in the
emitted JS. Stubs here exist so that IDE autocomplete and type-checkers
can read the surface every SPRAG user actually writes against.
"""

from dataclasses import dataclass
from typing import Any, Callable, Iterable, List, Optional, Type, TypeVar

F = TypeVar("F", bound=Callable[..., Any])
C = TypeVar("C", bound=type)
M = TypeVar("M", bound="Module")

EventHandler = Callable[..., Any]
"""DOM / bus / socket event callback."""

Cleanup = Callable[[], Any]
"""Cleanup function registered via ``add_cleanup``."""

Unsubscribe = Callable[[], Any]
"""Returned by subscriptions (``listen``, ``watch_state``, ``subscribe``)."""

TimerHandle = Any
"""Opaque handle returned by ``timeout`` / ``interval``."""


class BrowserElement:
    """Mounted DOM element handle used by browser-authored Python."""

    def query_selector(self, selector: str) -> Any: ...
    def query_selector_all(self, selector: str) -> Iterable[Any]: ...
    def querySelector(self, selector: str) -> Any: ...
    def querySelectorAll(self, selector: str) -> Iterable[Any]: ...
    def set_attribute(self, name: str, value: Any) -> None: ...
    def get_attribute(self, name: str) -> Any: ...
    def remove_attribute(self, name: str) -> None: ...
    def add_event_listener(self, event: str, fn: EventHandler) -> None: ...
    def remove_event_listener(self, event: str, fn: EventHandler) -> None: ...
    def __getattr__(self, name: str) -> Any: ...


class VirtualScrollerHandle:
    """Public handle exposed as ``self.virtual_scroll`` on decorated components."""

    def reset(self) -> None: ...
    def mount(self, element: Any) -> None: ...
    def unmount(self) -> None: ...
    def recycle(self) -> None: ...
    def rebind(self, options: Optional[dict] = ..., container: Optional[Any] = ...) -> None: ...
    def debug_state(self) -> dict[str, Any]: ...
    def acquire_child(self, chunk_index: int, child: Any, mount: Any) -> Any: ...
    def __getattr__(self, name: str) -> Any: ...

# ---------------------------------------------------------------------------
# Decorators
# ---------------------------------------------------------------------------

def debounce(seconds: float) -> Callable[[F], F]: ...
def throttle(seconds: float) -> Callable[[F], F]: ...
def animate(class_name: str = ...) -> Callable[[C], C]: ...
def virtual_scroll(
    *,
    chunk: int,
    max_chunks: int = ...,
    initial_chunks: int = ...,
    root: Optional[str] = ...,
    root_margin: str = ...,
    container_class: Optional[str] = ...,
    pool_size: int = ...,
    child_pool_size: int = ...,
    axis: str = ...,
) -> Callable[[C], C]: ...
def infinite_scroll(
    *,
    at: str,
    root: Optional[str] = ...,
    root_margin: str = ...,
    top_at: Optional[str] = ...,
    visible_chunks: Optional[int] = ...,
) -> Callable[[F], F]: ...

class RefDescriptor:
    selector: str
    def __init__(self, selector: str) -> None: ...
    def __set_name__(self, owner: type, name: str) -> None: ...
    def __get__(self, obj: Any, objtype: Optional[type] = ...) -> Any: ...

def ref(selector: str) -> Any: ...

# ---------------------------------------------------------------------------
# Generated-only namespace stubs
# ---------------------------------------------------------------------------

class _JSNamespaceStub:
    """Dynamic JS value exposed to browser-authored Python.

    Attribute access, calls, indexing, and truthiness compile to JavaScript.
    The concrete shape is intentionally user/runtime-defined.
    """

    def __init__(self, path: str) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __bool__(self) -> bool: ...

browser: _JSNamespaceStub
imports: _JSNamespaceStub

def createStateStore(
    initial_state: Optional[dict[str, Any]] = ...,
    options: Optional[dict[str, Any]] = ...,
) -> Any: ...
def createSelector(
    input_selectors: List[Callable[..., Any]],
    result_func: Callable[..., Any],
) -> Callable[..., Any]: ...

# ---------------------------------------------------------------------------
# Module — browser-side lifecycle owner
# ---------------------------------------------------------------------------

@dataclass
class Module:
    """Browser-side logic for DOM events, state, actions, sockets, and timers.

    Put setup in ``on_start()``. Common calls: ``self.delegate(...)``,
    ``self.set_state(...)``, ``self.call_action(...)``, ``self.on_socket(...)``.
    In ``Screen.render()``, call ``self.module(MyModule)``, seed state, then
    return ``hydrate(Component, module=module)``.
    """

    screen: Optional["Screen"] = ...
    state: dict[str, Any] = ...
    stores: list[Any] = ...
    element: BrowserElement = ...
    component: "Component" = ...

    def on_start(self) -> None: ...
    def on_stop(self) -> None: ...

    # DOM events
    def on(self, target: Any, event: str, fn: EventHandler) -> None: ...
    def off(self, target: Any, event: str, fn: EventHandler) -> None: ...
    def delegate(
        self, target: Any, event: str, selector: str, fn: EventHandler
    ) -> None: ...

    # Bus
    def listen(self, event: str, fn: EventHandler) -> Unsubscribe: ...
    def emit(self, event: str, data: Any = ...) -> None: ...

    # Managed timers
    def timeout(self, fn: Callable[[], Any], seconds: float) -> TimerHandle: ...
    def interval(self, fn: Callable[[], Any], seconds: float) -> TimerHandle: ...
    def clear_timeout(self, handle: TimerHandle) -> None: ...
    def clear_interval(self, handle: TimerHandle) -> None: ...

    # Lifecycle ownership
    def add_cleanup(self, fn: Cleanup) -> None: ...
    def adopt(self, child: Any) -> Any: ...
    def adopt_component(self, component: "Component") -> "Component": ...

    # State
    def set_state(self, new_state: dict[str, Any]) -> dict[str, Any]: ...
    def batch_state(self, fn: Callable[[], Any]) -> None: ...
    def watch_state(self, fn: Callable[..., Any]) -> Unsubscribe: ...
    def subscribe(self, store: Any, fn: Callable[..., Any]) -> Unsubscribe: ...
    def create_selector(
        self,
        deps: List[Callable[..., Any]],
        fn: Callable[..., Any],
    ) -> Callable[..., Any]: ...
    def provider(self, name: str) -> Any: ...

    # Server push
    def on_socket(self, event: str, fn: EventHandler) -> Unsubscribe: ...
    def off_socket(self, event: str, fn: EventHandler) -> None: ...
    def emit_socket(self, event: str, payload: Any = ...) -> None: ...
    def refetch_on_socket(
        self,
        event: str = ...,
        action: Optional[str] = ...,
        on_result: Optional[Callable[..., Any]] = ...,
        on_error: Optional[Callable[..., Any]] = ...,
    ) -> Unsubscribe: ...
    def join_topic(self, topic: str) -> None: ...
    def leave_topic(self, topic: str) -> None: ...

    # Actions
    def call_action(self, name: str, payload: Optional[dict[str, Any]] = ...) -> Any: ...
    def action_error_message(
        self, error: Any, fallback: Optional[str] = ...
    ) -> str: ...
    def form_data(self, source: Any) -> dict[str, Any]: ...
    def upload_form(
        self,
        name: str,
        source: Any,
        on_progress: Optional[Callable[..., Any]] = ...,
    ) -> Any: ...
    def upload(
        self,
        name: str,
        file: Any,
        payload: Optional[dict[str, Any]] = ...,
        on_progress: Optional[Callable[..., Any]] = ...,
    ) -> Any: ...
    def navigate(self, target: str, options: Optional[dict[str, Any]] = ...) -> None: ...
    def set_metadata(self, metadata: dict[str, Any], options: Optional[dict[str, Any]] = ...) -> None: ...

# ---------------------------------------------------------------------------
# Component — browser-side DOM owner
# ---------------------------------------------------------------------------

@dataclass
class Component:
    """Browser-side DOM renderer.

    Implement ``render(props=None)`` to return a ``ui.*`` tree. Use
    ``self.props``, ``self.state``, ``self.refs``, and ``self.set_state(...)``
    for local rendering behavior.
    """

    props: dict[str, Any] = ...
    state: dict[str, Any] = ...
    refs: dict[str, Any] = ...
    element: BrowserElement = ...
    virtual_scroll: VirtualScrollerHandle = ...

    # Required override
    def render(self, props: Optional[dict[str, Any]] = ...) -> Any: ...

    # Lifecycle overrides
    def on_start(self) -> None: ...
    def on_stop(self) -> None: ...

    def on_start(self) -> None: ...
    def on_stop(self) -> None: ...

    # Operational mount/unmount
    def mount(self, parent: Any) -> None: ...
    def mount_before(self, sibling: Any) -> None: ...
    def unmount(self) -> None: ...

    # State
    def set_state(self, new_state: dict[str, Any]) -> dict[str, Any]: ...
    def set_state_sync(self, new_state: dict[str, Any]) -> dict[str, Any]: ...

    # DOM events
    def on(self, target: Any, event: str, fn: EventHandler) -> None: ...
    def off(self, target: Any, event: str, fn: EventHandler) -> None: ...
    def delegate(
        self, target: Any, event: str, selector: str, fn: EventHandler
    ) -> None: ...

    # Bus
    def listen(self, event: str, fn: EventHandler) -> Unsubscribe: ...
    def emit(self, event: str, data: Any = ...) -> None: ...

    # Timers
    def timeout(self, fn: Callable[[], Any], seconds: float) -> TimerHandle: ...
    def interval(self, fn: Callable[[], Any], seconds: float) -> TimerHandle: ...

    # Lifecycle ownership
    def add_cleanup(self, fn: Cleanup) -> None: ...
    def adopt(self, child: Any) -> Any: ...
    def create_selector(
        self,
        deps: List[Callable[..., Any]],
        fn: Callable[..., Any],
    ) -> Callable[..., Any]: ...

    # Forms / uploads
    def form_data(self, source: Any) -> dict[str, Any]: ...
    def upload_form(
        self,
        name: str,
        source: Any,
        on_progress: Optional[Callable[..., Any]] = ...,
    ) -> Any: ...
    def upload(
        self,
        name: str,
        file: Any,
        payload: Optional[dict[str, Any]] = ...,
        on_progress: Optional[Callable[..., Any]] = ...,
    ) -> Any: ...
    def action_error_message(
        self, error: Any, fallback: Optional[str] = ...
    ) -> str: ...
    def navigate(self, target: str, options: Optional[dict[str, Any]] = ...) -> None: ...
    def set_metadata(self, metadata: dict[str, Any], options: Optional[dict[str, Any]] = ...) -> None: ...

# ---------------------------------------------------------------------------
# Screens + mount declarations
# ---------------------------------------------------------------------------

@dataclass
class Screen:
    """Server-rendered page view.

    Declare ``modules = [MyModule]``. In ``render(data)``, call
    ``self.module(MyModule)``, seed state, then return ``hydrate(...)`` or
    ``ui.*`` markup.
    """

    data: dict[str, Any] = ...
    modules: list[type[Module]] = ...

    def module(self, module_type: Type[M]) -> M: ...
    def render(self, data: dict[str, Any]) -> Any: ...
    @classmethod
    def sample_data(cls) -> dict[str, Any]: ...

@dataclass(frozen=True)
class SSRMount:
    component: Any
    props: dict[str, Any]

@dataclass(frozen=True)
class HydrateMount:
    component: Any
    module: Optional[Any] = ...
    props: dict[str, Any] = ...

def ssr(component: Type[Component], **props: Any) -> SSRMount: ...
def hydrate(
    component: Type[Component],
    *,
    module: Optional[Module] = ...,
    props: Optional[dict[str, Any]] = ...,
) -> HydrateMount:
    """Mount a browser Component, optionally owned by a Module.

    If ``props`` is omitted and ``module`` is provided, the component starts
    with the module's current state.
    """
    ...
