"""Type stubs for sprag.runtime.dom."""

from typing import Any, Iterable, Optional

Element = Any


def query(selector: str, parent: Optional[Element] = ...) -> Element: ...
def query_all(selector: str, parent: Optional[Element] = ...) -> list[Element]: ...
def show(element: Element) -> None: ...
def hide(element: Element) -> None: ...
def toggle(element: Element) -> None: ...
def css(element: Element, styles: dict[str, Any]) -> None: ...
def attr(element: Element, attrs: dict[str, Any]) -> None: ...
def clear(element: Element) -> None: ...
def create_icon(svg_string: str, class_name: str = ...) -> Element: ...
def animate_in(element: Element, **options: Any) -> None: ...
def animate_out(element: Element, **options: Any) -> None: ...
def append(parent: Element, child: Element) -> None: ...
def prepend(parent: Element, child: Element) -> None: ...
def insert_before(parent: Element, child: Element, reference: Element) -> None: ...
def remove(element: Element) -> None: ...
def batch_append(parent: Element, children: Iterable[Element]) -> None: ...
def clear_pool(key: Optional[str] = ...) -> None: ...
