"""Type stubs for sprag.runtime.request."""

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Optional, Union


@dataclass(frozen=True)
class UploadedFile:
    """Uploaded multipart file available in controller actions.

    Use ``read()`` for bytes, ``text()`` for decoded text, ``save(path)`` to
    persist it, and ``size`` for the byte count.
    """

    name: str
    filename: str
    content_type: Optional[str] = ...
    data: bytes = ...
    headers: dict[str, Any] = ...

    @property
    def size(self) -> int: ...
    def read(self) -> bytes: ...
    def text(self, encoding: str = ..., errors: str = ...) -> str: ...
    def save(self, path: Union[str, Path]) -> Path: ...
    @classmethod
    def from_path(
        cls,
        path: Union[str, Path],
        *,
        name: str,
        filename: str,
        content_type: Optional[str] = ...,
    ) -> "UploadedFile": ...


@dataclass
class Request:
    """Current HTTP request for ``Controller.load()`` and actions.

    Read route params from ``params``, query values from ``query``, form fields
    from ``form``, uploads from ``file(...)``/``files_list(...)``, and auth
    context from ``session``, ``user``, and ``active_profile``.
    """

    path: str
    params: dict[str, Any] = ...
    query: dict[str, Any] = ...
    headers: dict[str, str] = ...
    method: str = ...
    body: bytes = ...
    request_id: Optional[str] = ...
    session_id: Optional[str] = ...
    cookies: dict[str, str] = ...
    session: Any = ...
    user: Any = ...
    active_profile: Any = ...
    content_type: Optional[str] = ...
    form: dict[str, Any] = ...
    files: dict[str, Union[UploadedFile, list[UploadedFile]]] = ...

    def file(self, name: str, default: Any = ...) -> Any: ...
    def files_list(self, name: str) -> list[UploadedFile]: ...
