"""Type stubs for sprag.runtime.request."""

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Optional, Union


@dataclass(frozen=True)
class UploadedFile:
    """Uploaded multipart file exposed to SPRAG controllers."""

    name: str
    filename: str
    content_type: Optional[str] = ...
    data: bytes = ...
    headers: dict[str, Any] = ...

    @property
    def size(self) -> int: ...
    def read(self) -> bytes: ...
    def text(self, encoding: str = ..., errors: str = ...) -> str: ...
    def save(self, path: Union[str, Path]) -> Path: ...
    @classmethod
    def from_path(
        cls,
        path: Union[str, Path],
        *,
        name: str,
        filename: str,
        content_type: Optional[str] = ...,
    ) -> "UploadedFile": ...


@dataclass
class Request:
    """Request snapshot plus per-request runtime session/auth state."""

    path: str
    params: dict[str, Any] = ...
    query: dict[str, Any] = ...
    headers: dict[str, str] = ...
    method: str = ...
    body: bytes = ...
    request_id: Optional[str] = ...
    session_id: Optional[str] = ...
    cookies: dict[str, str] = ...
    session: Any = ...
    user: Any = ...
    active_profile: Any = ...
    content_type: Optional[str] = ...
    form: dict[str, Any] = ...
    files: dict[str, Union[UploadedFile, list[UploadedFile]]] = ...

    def file(self, name: str, default: Any = ...) -> Any: ...
    def files_list(self, name: str) -> list[UploadedFile]: ...
