"""Type stubs for sprag.runtime.stores."""

from typing import Any, Callable, Optional, Union

Selector = Union[str, Callable[[dict[str, Any]], Any]]
Unsubscribe = Callable[[], Any]


class StoreBridge:
    """Server-side handle to a SPRAG store; browser-side this becomes a JS import."""

    name: str
    initial: dict[str, Any]
    debug: bool

    def __init__(self, name: str, initial: Optional[dict[str, Any]] = ..., *, debug: bool = ...) -> None: ...
    def get(self, path: Optional[str] = ..., default: Any = ...) -> Any: ...
    def get_state(self) -> dict[str, Any]: ...
    def snapshot(self) -> dict[str, Any]: ...
    def set(self, path: str, value: Any) -> Any: ...
    def patch(self, partial: dict[str, Any]) -> dict[str, Any]: ...
    def update(self, mutator: Callable[[dict[str, Any]], Any]) -> dict[str, Any]: ...
    def delete(self, path: str) -> Any: ...
    def clear(self) -> None: ...
    def reset(self) -> dict[str, Any]: ...
    def subscribe(
        self,
        fn: Callable[[Any], Any],
        *,
        selector: Optional[Selector] = ...,
        immediate: bool = ...,
    ) -> Unsubscribe: ...
    def listen(self, path: str, fn: Callable[[Any], Any]) -> Unsubscribe: ...
    def select(self, selector: Selector, default: Any = ...) -> Any: ...


def store(name: str, *, initial: Optional[dict[str, Any]] = ..., debug: bool = ...) -> StoreBridge: ...
def declared_stores() -> list[StoreBridge]: ...
def store_fingerprint(stores: Optional[list[StoreBridge]] = ...) -> str: ...
def reset_store_registry() -> None: ...
