"""Type stubs for sprag.runtime.ui.

Explicit common HTML tag factories are listed so IDE autocomplete surfaces
them under ``ui.<TAB>``. Unknown tags fall through to ``__getattr__`` and
still return ``ElementNode`` factories.
"""

from dataclasses import dataclass
from typing import Any, Callable, Iterable, Optional, Union

from .browser import HydrateMount, SSRMount

@dataclass
class ElementNode:
    tag: str
    attrs: dict
    children: list

@dataclass
class ForNode:
    items: Any
    key: Any = ...
    render: Optional[Callable[..., Any]] = ...
    pool_key: Optional[str] = ...
    grid_opts: Optional[dict] = ...

@dataclass
class LazyImageNode:
    src: str
    placeholder: Optional[str] = ...
    attrs: dict = ...

@dataclass
class HTMLNode:
    html: str

UINode = Union[ElementNode, ForNode, LazyImageNode, HTMLNode, HydrateMount, SSRMount]
"""Any node the renderer accepts as a tree node."""

UIChild = Union[UINode, str, int, float, None]
"""A single child slot — node, primitive text, or ``None`` (skipped)."""

UIChildren = Union[UIChild, Iterable[UIChild]]
"""Children may be passed individually or as a flattenable iterable."""

UIKey = Union[str, Callable[[Any], Any], None]
"""``ui.For`` / ``ui.Grid`` key: field name, callable, or positional fallback."""

UIRender = Callable[..., UIChild]
"""``ui.For`` / ``ui.Grid`` render callback: ``(item)`` or ``(item, index)``."""

ElementFactory = Callable[..., ElementNode]
"""Return type of ``ui.<tagname>`` — call with children + attrs."""

def _resolve_key(key: UIKey, item: Any, index: int) -> str: ...

class UIFactory:
    # ----- Rendering primitives -----

    def For(
        self,
        items: Iterable[Any],
        *,
        key: UIKey = ...,
        render: Optional[UIRender] = ...,
        pool_key: Optional[str] = ...,
    ) -> ForNode:
        """Keyed list. Compiles to Ragot's ``renderList`` on the client.

        Example:
            ui.For(items, key="id", render=lambda item: ui.li(item["label"]))
            ui.For(todos, key=lambda todo: todo["id"], render=TodoRow)
        """
        ...

    def Grid(
        self,
        items: Iterable[Any],
        *,
        key: UIKey = ...,
        render: Optional[UIRender] = ...,
        pool_key: Optional[str] = ...,
        columns: Optional[int] = ...,
        column_width: Optional[Union[int, str]] = ...,
        gap: Optional[Union[int, str]] = ...,
        apply_grid_styles: bool = ...,
    ) -> ForNode:
        """Keyed grid. Compiles to Ragot's ``renderGrid`` on the client.

        Example:
            ui.Grid(cards, key="id", columns=3, gap="1rem", render=Card)
            ui.Grid(products, column_width="16rem", render=ProductTile)
        """
        ...

    def LazyImage(
        self,
        src: str,
        *,
        placeholder: Optional[str] = ...,
        **attrs: Any,
    ) -> LazyImageNode:
        """Lazy-loaded image. Compiles to a ``createLazyLoader`` install.

        Example:
            ui.LazyImage("/hero.jpg", placeholder="/hero-blur.jpg", alt="Hero")
            ui.LazyImage(article["image"], class_="article-image")
        """
        ...

    def HTML(self, html: str) -> HTMLNode: ...

    # ----- Explicit common HTML tag factories (for autocomplete) -----

    def div(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def span(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def p(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def a(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def button(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def input(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def textarea(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def select(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def option(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def label(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def form(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def fieldset(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def legend(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def h1(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def h2(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def h3(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def h4(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def h5(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def h6(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def ul(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def ol(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def li(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def img(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def video(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def audio(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def source(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def picture(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def table(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def thead(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def tbody(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def tfoot(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def tr(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def td(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def th(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def header(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def footer(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def main(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def nav(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def section(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def article(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def aside(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def details(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def summary(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def dialog(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def code(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def pre(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def em(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def strong(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def small(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def br(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def hr(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def blockquote(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def figure(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def figcaption(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def canvas(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def svg(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def path(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def script(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def style(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def link(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...
    def meta(self, *children: UIChildren, **attrs: Any) -> ElementNode: ...

    # ----- Fallback for any other tag -----

    def __getattr__(self, tag: str) -> ElementFactory: ...

ui: UIFactory
