"""Generate project-level SPRAG type aliases from a build manifest."""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Iterable, Optional, Union


HEADER = """# Auto-generated by SPRAG. Do not edit.
from typing import Literal

"""


def emit_project_types(
    manifest_path: Union[str, Path] = ".sprag/manifest.json",
    output_path: Optional[Union[str, Path]] = None,
) -> Path:
    """Read a SPRAG manifest and emit project-local type aliases."""
    manifest_file = Path(manifest_path)
    if output_path is None:
        output_file = manifest_file.with_name("sprag_project_types.pyi")
    else:
        output_file = Path(output_path)
    manifest = json.loads(manifest_file.read_text(encoding="utf-8"))
    output_file.parent.mkdir(parents=True, exist_ok=True)
    package_init = output_file.parent / "__init__.py"
    if not package_init.exists():
        package_init.write_text("", encoding="utf-8")
    package_marker = output_file.parent / "py.typed"
    if not package_marker.exists():
        package_marker.write_text("", encoding="utf-8")
    stale_types_file = output_file.with_name("types.pyi")
    if stale_types_file != output_file and stale_types_file.exists():
        stale_types_file.unlink()
    output_file.write_text(render_project_types(manifest), encoding="utf-8")
    return output_file


def render_project_types(manifest: dict) -> str:
    """Return the generated project type content for a manifest dictionary."""
    routes = manifest.get("routes", [])
    mounts = manifest.get("mounts", [])
    route_paths = _unique(entry.get("path") for entry in routes)
    mount_paths = _unique(entry.get("path") for entry in mounts)
    action_names = _unique(
        action
        for entry in list(routes) + list(mounts)
        for action in entry.get("actions", [])
    )
    store_names = _unique(entry.get("name") for entry in manifest.get("stores", []))
    module_aliases = _unique(
        alias
        for entry in list(routes) + list(mounts)
        for alias in (entry.get("modules") or {}).keys()
    )

    lines = [HEADER.rstrip(), ""]
    lines.append(_literal_alias("RoutePath", route_paths))
    lines.append(_literal_alias("MountPath", mount_paths))
    lines.append(_literal_alias("SurfacePath", _unique([*route_paths, *mount_paths])))
    lines.append(_literal_alias("ActionName", action_names))
    lines.append(_literal_alias("StoreName", store_names))
    lines.append(_literal_alias("ModuleAlias", module_aliases))

    surface_aliases: dict[str, tuple[str, ...]] = {}
    for entry in routes:
        values = tuple(_unique(entry.get("actions", [])))
        if values:
            _add_surface_alias(surface_aliases, entry, values, suffix="Action")
    for entry in mounts:
        values = tuple(_unique(entry.get("actions", [])))
        if values:
            _add_surface_alias(surface_aliases, entry, values, suffix="Action")

    if surface_aliases:
        lines.append("")
        for alias in sorted(surface_aliases):
            lines.append(_literal_alias(alias, surface_aliases[alias]))

    return "\n".join(lines).rstrip() + "\n"


def _literal_alias(name: str, values: Iterable[str]) -> str:
    values = tuple(_unique(values))
    if not values:
        return f"{name} = str"
    rendered = ", ".join(repr(value) for value in values)
    return f"{name} = Literal[{rendered}]"


def _add_surface_alias(
    aliases: dict[str, tuple[str, ...]],
    entry: dict,
    values: tuple[str, ...],
    *,
    suffix: str,
) -> None:
    base = _pascal_identifier(entry.get("name") or entry.get("path") or "Surface")
    alias = f"{base}{suffix}"
    if alias not in aliases or aliases[alias] == values:
        aliases[alias] = values
        return
    index = 2
    while f"{alias}{index}" in aliases and aliases[f"{alias}{index}"] != values:
        index += 1
    aliases[f"{alias}{index}"] = values


def _unique(values: Iterable[object]) -> list[str]:
    result: list[str] = []
    seen: set[str] = set()
    for value in values:
        if not isinstance(value, str) or not value:
            continue
        if value in seen:
            continue
        seen.add(value)
        result.append(value)
    return sorted(result)


def _pascal_identifier(value: str) -> str:
    parts = [part for part in re.split(r"[^0-9A-Za-z]+", value) if part]
    if not parts:
        return "Surface"
    candidate = "".join(part[:1].upper() + part[1:] for part in parts)
    if candidate[:1].isdigit():
        candidate = f"Surface{candidate}"
    return candidate
